GET http://localhost:3001/api/users/61bb0211d23252eed945a1d7

###

GET http://localhost:3001/api/users/auth/Niek

###

GET http://localhost:3001/api/poules/userpoules?id=61bb0211d23252eed945a1d7


###
POST http://localhost:3001/api/poules
Content-Type: application/json

{
    "name": "My amazing poule",
    "user": "61bb0211d23252eed945a1d7"
}

###
POST http://localhost:3001/api/poules/add
Content-Type: application/json

{
    "name": "Jeroen",
    "poule" : "61c0a9a617bfa90cab27091a"
}

###
GET http://localhost:3001/api/prediction/61c2fc9325044a7930e56082


###


POST http://localhost:3001/api/prediction
Content-Type: application/json

{
    "userId": "61bb02c6d23252eed945a1d8",
    "poule": "61bb0465d23252eed945a1da",
    "round": 1,
    "name": "Bahrain Grand Prix",
    "prediction": ["VER", "HAM", "BOT", "PER", "NOR", "RIC","SAI", "ALO","LEC", "OCO", "RUS", "GAS", "TSU", "GIO", "RAI", "LAT", "MSC", "MAZ", "VET", "STR"]
}