GET http://localhost:3001/api/users/61bb0211d23252eed945a1d7

###

GET http://localhost:3001/api/users/auth/Niek

###

GET http://localhost:3001/api/poules/userpoules?id=61bb0211d23252eed945a1d7


###
POST http://localhost:3001/api/poules
Content-Type: application/json

{
    "name": "My amazing poule",
    "user": "61bb0211d23252eed945a1d7"
}

###
POST http://localhost:3001/api/poules/add
Content-Type: application/json

{
    "name": "Jeroen",
    "poule" : "61c09b97803a1e8501286806"
}